version: '3.8'

services:
  procurement-agent:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: procurement
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
